### PR TITLE
Forward Tagger Energy Correction Function

### PR DESCRIPTION
**Pull request by asligonulacar**
Implemented the Forward Tagger energy correction function as an IGUANA algorithm. Please let me know if I have made any errors. This is mainly a placeholder until a more complicated algorithm can be implemented. This function is currently only validated for Fall 2018 outbending data.

### CODE REVIEW

**Comment by c-dilks** [comment]
Do you need ROOT dependence for this algorithm? I plan to add it soon...

**Comment by c-dilks** [comment]
> Do you need ROOT dependence for this algorithm? I plan to add it soon...

We now allow algorithms to depend on ROOT; however, try to use the new `ROOT::Math` vectors rather than `TLorentzVector`. The updated `LorentzTransformer` algorithm demonstrates a boost with `ROOT::Math::Boost`.

**Comment by c-dilks** [comment]
Some other things of note:
- add your algorithm to `src/iguana/algorithms/meson.build` so that it's included in the build; if it depends on ROOT, set `needs_ROOT` to true
- add your name to the `CODEOWNERS` file and attach it to your algorithm's files

**Comment by dglazier** [comment]
Hi folks,
  What is the status of the iguana FT correction ? It looks like this has not been merged yet, and there is a test fail. Does this need some work ? I would like to try out this algorithm.
Cheers
Derek

**Comment by c-dilks** [comment]
@dglazier it needed some work to catch up with the `main` branch. I updated this algorithm and spot checked the output, but it needs validation, in particular a "Validator" type algorithm (see, _e.g._, `MomentumCorrectionValidator` which makes plots of the corrections from the `MomentumCorrection` algorithm).

@asligonulacar can you check the new version of your algorithm, and would you be willing to write such a validator?

**Review by c-dilks — APPROVED** [review]

**Pull request merged**
