### PR TITLE
fix: use `hipo` iterators for proper `bank` row filtering

### PR DESCRIPTION
**Pull request by c-dilks**

### CODE REVIEW

**Review by rtysonCLAS12 — DISMISSED** [review]
looks good to me

**Comment by c-dilks** [comment]
Rebased and resolved conflicts with #179

**Comment by c-dilks** [comment]
Because of the rebase and the age of this PR, I will test the output of the examples and validators again, to make sure there are no differences.

**Comment by c-dilks** [comment]
No diffs

**Pull request merged**
