### PR TITLE
refactor!: organize algorithms in subdirectories

### PR DESCRIPTION
**Pull request by c-dilks**
The number of files per algorithms has been growing, so the algorithms are now organized into individual subdirectories, with the following files:

| File(s) | Description |
| --- | --- |
| `Algorithm.{h,cc}` |        the algorithm implementation |
| `Validator.{h,cc}` | algorithm validator |
| `Config.yaml` | algorithm configuration |
| `Bindings.cc` | C bindings (for Fortran) |

- This change also allows algorithms to include more classes and headers, if needed.
- This is a **breaking change** for consumers which include algorithm headers. For example:
```cpp
#include <iguana/algorithms/clas12/MomentumCorrection.h>             # before the change
#include <iguana/algorithms/clas12/MomentumCorrection/Algorithm.h>   # after the change
```

### Additional changes
- The `iguana-example-*` executables also have been renamed, to exclude the numbers
- Starter algorithm script `make_template.sh` has been renamed to `make_starter.sh`

### CODE REVIEW

**Comment by dglazier** [comment]
When is the expected merge  for this branch? I would like to add the iguana stuff to the clas12root release, but would prefer to wait for this refactorisation if it is going to be soon.

**Comment by c-dilks** [comment]
> When is the expected merge for this branch?

Early next week, unless we run into any difficult issues here.

**Comment by c-dilks** [comment]
@dglazier CI checks pass now. I will review the changes on Monday; I also requested your review, in case you'd like to take a second look or have any feedback.

**Comment by dglazier** [comment]
Hi Chris,
  It works fine for me. The only slight issue is you end up with long include paths e.g.

      #include <iguana/algorithms/clas12/ZVertexFilter/Algorithm.h>

Cheers
Derek

**Pull request merged**
