### PR TITLE
feat: add ROOT macro example

### LINKED ISSUE #159: add ROOT macro example
Something like:
```cpp
gSystem->Load("install/lib/libhipo4.so");
gSystem->Load("install/lib/libIguanaServices.so");
gSystem->Load("install/lib/libIguanaAlgorithms.so");
#include "install/include/hipo4/bank.h"
#include "install/include/iguana/algorithms/Algorithm.h"
```

### PR DESCRIPTION
**Pull request by c-dilks**
close #159

TODO
- [x] CI tests
- [x] add `ROOT_INCLUDE_PATH` to modulefiles
- [x] add `IGUANA` to modulefiles

### CODE REVIEW

**Comment by c-dilks** [comment]
@dglazier, this adds a simple ROOT macro example, which relies on `ROOT_INCLUDE_PATH` and `{,DY}LD_LIBRARY_PATH` to be set correctly; `this_iguana.sh` will now prepend `ROOT_INCLUDE_PATH`, and we can make sure the modulefile does as well.

Will this work for you, or do you need anything else to support `clas12root` integration?

**Comment by dglazier** [comment]
For clas12root I do not use the .sh file. It just needs IGUANA set to point to the install directory. I was able to get round ROOT_INCLUDE_PATH by adding

       gInterpreter->AddIncludePath(IGUANA+"/include");

To the Load script. Previously I had gSystem->AddIncludePath which does not work for some reason.

**Comment by dglazier** [comment]
For clas12root I prefer users just need to set 1 variable e.g. IGUANA, HIPO, QADB,... clas12root can then handle the linking at runtime, rather than have users having to set ROOT_INCLUDE_PATH etc.

**Comment by c-dilks** [comment]
What about users who want to run `iguana` with a ROOT macro, not using `clas12root`? If `ROOT_INCLUDE_PATH` isn't set, then they have to figure out the paths themselves, or we could do it for them, something like:
```cpp
// somehow get the `stdout` of these, handle errors, etc.
gROOT->ProcessLine(".! pkg-config iguana --variable include")
gROOT->ProcessLine(".! pkg-config iguana --variable dep_includedirs")

// concatenate, tokenize by `:`, then for each path:
gInterpreter->AddIncludePath("-I" + path);
```
This sort of thing could be buried in a `loadIguana.C`, similar to `LoadClas12Root.C`; `meson` could even be used to generate such a file, to avoid having to run `pkg-config` at all (but then that might worsen #212).

OTOH, with `ROOT_INCLUDE_PATH`, the only other things a user needs in their ROOT macro is `gSystem->Load("libIguanaAlgorithms")` and the include directives. On `ifarm` this variable can be set for them in the module file; on local builds, users will either install to the system default location (probably not a great idea) or will `source this_iguana.sh`.

> The .sh file uses pkg-config variables to set the environment variables; since clas12root uses CMake, perhaps it could use [pkg_get_variable](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_get_variable) to access the variables dep_includedirs and includedir (and others, if needed).

This might be what you want if you want to avoid `ROOT_INCLUDE_PATH` in `clas12root`; you could use the results in `gInterpreter->AddIncludePath` calls.

**Comment by dglazier** [comment]
I think ROOT users should absolutely use the way you think is best. I was just referring to CLAS12ROOT usage. I don't want to include iguana in the build as it is not necessary, but just load the libs and includes at run-time, this is done simply with the environment variables. 
It looks like in general there can be some conflicts for FMT at least which can be fixed by ROOT_INCLUDE_PATH, or by including an FMT_IGUANA variable, and me modifying LoadIguana.C to use it.
The advantage of environment variables is they are simple to use and do not require additional knowledge or dependencies. At some universities students will be on very old systems and will not be able to debug or fix build errors or have access to pkg or modern build systems. Also they come at no extra cost, you could just set these things in the .sh script, which on ifarm presumably gets passed into the clas12 environment. Then I am all done and do not need to do anymore work on this for now. You could even set IGUANA_INCS and IGUANA_LIBS if you are worried about $IGUANA/include not being safe.
I appreciate the pkg-config and iguana build system are more optimal, however I have no time to make significant changes to clas12root build and it seems there is a straightforward solution. I am happy for Hall B to take over maintenance of any of the clas12root stuff and fix this (and CI).

**Pull request merged**
